### ISSUE TITLE
Inconsistency between Rajamani & code (?)

### ISSUE THREAD

**Issue by namnatulco** [michele-segata/plexe-sumo#1]
I was having a look at the ACC controller implementation ([`_acc`](https://github.com/michele-segata/plexe-sumo/blob/plexe-2.0/sumo/src/microsim/cfmodels/MSCFModel_CC.cpp#L415)) in Plexe-2.0, and I think I found an error here:
```return -1.0 / headwayTime * (egoSpeed - predSpeed + myLambda * (-gap2pred + headwayTime * egoSpeed + 2));```

For some reason, a constant value of 2 is added. After having a look at the book (eq 6.18), I think that this 2 represents the length of the preceding vehicle. However, this does not correspond with the length value defined in the standard [freeway.rou.xml](https://github.com/michele-segata/plexe-veins/blob/plexe-2.0/examples/platooning/sumocfg/freeway.rou.xml) in plexe-veins. Am I missing something here, or is this intentional, because `gap2pred` somehow includes part of the vehicle length already?

**Comment by michele-segata** [comment]
Hi
The 2 additional meters are used as a standstill distance. If you take the formula as is, after a complete stop the vehicles would touch. This way the distance at zero speed is 2 meters.

**Comment by namnatulco** [comment]
Thanks!
